# Generated by Django 4.1.7 on 2023-03-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_annonce"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Annonce",
            new_name="Listing",
        ),
    ]
