# Generated by Django 4.1.7 on 2023-03-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_rename_annonce_listing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="band",
            old_name="nom",
            new_name="name",
        ),
    ]
